### ISSUE TITLE
Make it easier for customers to find out what value to provide for a discriminator property in a polymorphic type

### ISSUE THREAD

**Issue by amarzavery** [Azure/ms-rest-js#65] opened 2018-04-23 17:03 UTC
Previously, customers have complained that they find it difficult to provide a value for the discriminator property. Moreover they have argued that while declaring the model type if I am saying that it is a cat then why do you ask me to provide that information. Doesn't the sdk already know this?

Well that is actually true. The sdk knows this information but this info is in the model mapper. At runtime (i.e. in javascript that gets executed), the sdk gets a json object. We validate that json object against the model mapper that we know is associated for that operation. However, we would only know whether it is an Animal or a Cat or a Dog, based on what value the customer provides for the discriminator property.

Our model types are TypeScript Interfaces. We have chosen them to be interfaces over classes for multiple reasons. Typescript restricts us from providing default values for a property of an interface and it makes sense. However, that does not help us in solving the above problem faced by our customers.

Possible solutions that come to my mind are as follows:
- Ensure that the documentation of the discriminator property contains all the possible values in the documentation of that property. This will help customers who do not want to use TS.
- Create an **enum of discriminator values**. This allows us to map x-ms-discriminator values as value of the enum. The discriminator property is specified in every model with the possible value for that type.
```js
export enum AnimalType {
  Animal = "Animal",
  Cat = "Cat",
  Dog = "Dog"
}
export interface Animal {
  type: AnimalType; // Here I have provided the enum as a type
  id: number;
  name: string;
}

export interface Cat extends Animal {
  type: AnimalType.Cat; // Here it is the specific type Cat
  weight: number;
}

export interface Dog extends Animal {
  type: AnimalType.Dog; // Specific type Dog
  color: string;
}

const a: Animal = {
  id: 1,
  name: "SomeAnimal",
  type: AnimalType.Animal // However one still needs to specify the type otherwise TS complains
}

const c: Cat = {
  id: 2,
  name: "BobCat",
  weight: 20,
  type: AnimalType.Cat // However one still needs to specify the type otherwise TS complains. Couldn't get TS to auto populate the value for type. However this is still better as it guides the customer to the right path.
}
```
- Create a **type of possible discriminator values**. For more context take a look over [here](https://basarat.gitbooks.io/typescript/docs/types/discriminated-unions.html).
```js
export type AnimalType : "Animal" | "Cat" | "Dog".

export interface Animal {
  type: AnimalType;
  id: number;
  name: string;
}

export interface Cat extends Animal {
  weight: number;
}

export interface Dog extends Animal {
  color: string;
}

const a: Animal = {
  id: 1,
  name: "SomeAnimal",
  type: "Animal"
}

const c: Cat = {
  id: 2,
  name: "BobCat",
  weight: 20,
  type: "Cat"
}
```

**Comment by RikkiGibson** [comment] 2018-04-23 19:43
Let's ensure the documentation for a discriminator property shows all the possible values and make its type a union of literal strings (`"Animal" | "Cat" | "Dog"`). The string enum approach is not as nice for TypeScript developers because it makes it a type error to provide `"Animal"` instead of `AnimalType.Animal`.

**Comment by RikkiGibson** [comment] 2018-04-23 20:12
Namespaces can also be used to give a good completion experience and might look like:
```ts
export type AnimalType = "Animal" | "Cat" | "Dog";
export namespace AnimalType {
  export const Animal = "Animal";
  export const Cat = "Cat";
  export const Dog = "Dog";
}

let foo: AnimalType = "Animal";
let bar: AnimalType = AnimalType.Animal;
```

It's worth noting that `type` declarations don't exist after compilation while `enum` and `namespace` declarations will.

**Comment by daschult** [comment] 2018-06-27 21:48
Duplicate of https://github.com/Azure/azure-sdk-for-node/issues/2960.

**Closed by daschult** 2018-06-27 21:48 UTC
