### ISSUE TITLE
Build Error from serializer.ts file

### ISSUE THREAD

**Issue by RupengLiu** [Azure/ms-rest-js#421] opened 2021-02-04 02:26 UTC
**Package Version**: __2.0.4_____
- [ ] **nodejs**
   - **nodejs version**: ______
   - **os name/version**: _____
- [ ] **browser**
    - **name/version**: ____
**Describe the bug**
I'm working on upgrade AzureApimanagement vscode extension's SDK to @azure/ms-rest-js, but after I start the build, I got a bunch of error from the serializer.ts file from the SDK, as shown in the following picture
 
![image](https://user-images.githubusercontent.com/29927264/106836027-3c975e00-664d-11eb-8f92-530509c39a70.png)

**To Reproduce**
1. add the SDK to dependency
2. build the project

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by RupengLiu** [comment] 2021-02-04 19:34
is there a workaround for this?

**Comment by jeremymeng** [comment] 2021-02-05 23:37
This was seen when migrating from old `azure-arm-*` packages to newer `@azure/arm-*` packages.

-skipLibCheck disabled type checking but is not a good solution. Re-open for investigation.

**Comment by jeremymeng** [comment] 2021-02-09 00:06
Discussed with @RupengLiu offline, this was caused by importing submodule.  When importing from @azure/ms-rest-js the issue is gone. There's another error about "RequestInit" but it's the same issue tracked by #367.  Closing

**Closed by jeremymeng** 2021-02-09 00:06 UTC
